---

- hosts: ansiblehost

  tasks:

  - name: remove image
    command: docker rmi --force birdseyrk/activemqartemis 
    ignore_errors: yes

  - name: remove image
    command: docker rmi --force container_activemqartemis
    ignore_errors: yes

  - name: remove image
    command: docker rmi --force birdseyrk/activemqartemis 
    ignore_errors: yes

  - name: remove image
    command: docker rmi --force container_activemqartemis
    ignore_errors: yes

  - name: remove prune image 
    command: docker image prune --force 
    ignore_errors: yes
